### ISSUE TITLE
Stadt

### ISSUE THREAD

**Issue by brunsen** [SKacmaz/IVC#4]
Für den Film wird eine Western Stadt benötigt.
Abnahmekriterien: 
- [x] Straße muss erkennbar sein
- [x] Cowboys passen in die Straße
- [x] Gebäude sind mindestens doppelt so groß wie die Figuren
- [x] Genügend Gebäude für eine Straße
- [x] Gebäude dürfen sich wiederholen
- [x] Gebäude müssen mit Texturen haben

**Comment by SKacmaz** [comment]
- Rotation der einzelnen Gebäude nicht möglich (oder etwa doch?)
