### ISSUE TITLE
Abspann + Credits

### ISSUE THREAD

**Issue by brunsen** [SKacmaz/IVC#7]
Nach der finalen Szene müssen Credits eingespielt werden. Darin sind folgende Informationen enthalten:
- [x] Skript/Idee von (Unsere Namen)
- [x] Umsetzung von ( Unsere Namen)
- [x] Nennung des Komponisten der Musik

**Comment by SKacmaz** [comment]
Mache ich am 11.01. fertig.

**Comment by SKacmaz** [comment]
- "Musik" fehlt noch
